# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
