# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_list_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(related_name='gameclaim_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
